version: '3'
services:
  docker-mysql:
    restart: always
    container_name: docker-mysql
    command: --default-authentication-plugin=mysql_native_password
    build: ./Lab3
    ports:
      - "6033:3306"
  lab6-app:
    restart: on-failure
    build: ./Lab6
    expose:
      - "10222"
    ports:
      - 10222:10222
    environment:
      WAIT_HOSTS: mysql:3306
    depends_on:
      - docker-mysql